# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0016_auto_20160518_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
